-- 0015_agent_role: the agent's operator-set role selector (SEA-1732 T10).
-- role is the operator-set selector for the agent's block-0 system prompt, its
-- source-of-truth field on the agent account (Matt-ruled 2026-08-07: source =
-- AgentAccount, mirroring persona). Where persona is an APPEND overlay layered
-- after the default prompt, role REPLACES block-0 via customSystemPrompt: the
-- label selects config/prompts/<role>/SYSTEM.md from the mounted config tree.
-- Empty string means no role — the agent keeps OMP's default block-0. It is
-- read at provision time and materialized to the container by the runner (a
-- separate lane); this migration is only the durable column + the store
-- round-trip that carries it.
--
-- NOT NULL DEFAULT '' so every existing and future agent row always has a value:
-- a joined agent row reads the empty default rather than NULL, matching the
-- "empty = no role" contract and keeping the create/read path branch-free.
ALTER TABLE agent_accounts ADD COLUMN role TEXT NOT NULL DEFAULT '';
